apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-reader
  namespace: demo

rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]